//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationService.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthenticationService.Shared.Resources.AuthMessages", typeof(AuthMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created, but your email is not yet confirmed. An email has been sent with instructions to complete your registration..
        /// </summary>
        public static string AccountCreationEmailConfirmationPendingMessage {
            get {
                return ResourceManager.GetString("AccountCreationEmailConfirmationPendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with email &apos;{0}&apos; was not found..
        /// </summary>
        public static string EmailNotFoundMessage {
            get {
                return ResourceManager.GetString("EmailNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with email &apos;{0}&apos; did not verify their email account..
        /// </summary>
        public static string EmailNotVerifiedMessage {
            get {
                return ResourceManager.GetString("EmailNotVerifiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding roles to the user. Please check that the roles exist..
        /// </summary>
        public static string ErrorAddingRolesMessage {
            get {
                return ResourceManager.GetString("ErrorAddingRolesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string FailedLoginMessage {
            get {
                return ResourceManager.GetString("FailedLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password provided is incorrect..
        /// </summary>
        public static string InvalidCurrentPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidCurrentPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email confirmation token is invalid or expired..
        /// </summary>
        public static string InvalidEmailConfirmationTokenMessage {
            get {
                return ResourceManager.GetString("InvalidEmailConfirmationTokenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP code entered is invalid or has expired. Please enter a new code..
        /// </summary>
        public static string InvalidOrExpiredOTPMessage {
            get {
                return ResourceManager.GetString("InvalidOrExpiredOTPMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset token is invalid or has expired..
        /// </summary>
        public static string InvalidPasswordResetTokenMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordResetTokenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token..
        /// </summary>
        public static string InvalidRefreshTokenMessage {
            get {
                return ResourceManager.GetString("InvalidRefreshTokenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset email has been sent with instructions to reset your password..
        /// </summary>
        public static string PasswordResetEmailSentMessage {
            get {
                return ResourceManager.GetString("PasswordResetEmailSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &apos;{0}&apos; was not found..
        /// </summary>
        public static string RoleNotFoundMessage {
            get {
                return ResourceManager.GetString("RoleNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication is required. An email has been sent with your one-time password (OTP). Please enter it to complete your login..
        /// </summary>
        public static string TwoFactorOtpVerificationPendingMessage {
            get {
                return ResourceManager.GetString("TwoFactorOtpVerificationPendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with email &apos;{0}&apos; already exists..
        /// </summary>
        public static string UserWithEmailAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("UserWithEmailAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} does not have any assigned roles..
        /// </summary>
        public static string UserWithNoRoleMessage {
            get {
                return ResourceManager.GetString("UserWithNoRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with UserName &apos;{0}&apos; already exists..
        /// </summary>
        public static string UserWithUserNameAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("UserWithUserNameAlreadyExistsMessage", resourceCulture);
            }
        }
    }
}
